### ISSUE TITLE
CHOOSE A TOPIC

### ISSUE THREAD

**Issue by jechnology** [jechnology/mms142-groupe-2020#1]
Netflix (Video Streaming) is now unavailable due to Group D picking it as their topic. 
We have to choose between:
- Internet of Things - 2 votes (Gerold, Joel, Joshua, Julia)
- AI and Drone for Disaster Response - 1 vote (Daizy)

Or if you guys have other ideas for our topic, feel free to discuss it here.

**Comment by juliaalexis** [comment]
Added my vote to IoT! Also included some resources on our [forum](https://myportal.upou.edu.ph/mod/forum/discuss.php?d=491556).

**Comment by jechnology** [comment]
WIth majority of the votes leaning towards Internet Of Things, we decided to select it as our final topic. Thus, this issue shall be closed now.
