### ISSUE TITLE
Meeting to align our plans!

### ISSUE THREAD

**Issue by juliaalexis** [jechnology/mms142-groupe-2020#3]
Hi! I think it's best to have a synchronous discussion regarding our plans. Our agenda can be the following:
- [x] align our knowledge and skills on using the platform/programming
- [x] discussing the outline of our project and flow
- [x] start assigning each member their respective part. 

Please do add your contact info below and your free schedule (preferably tomorrow ASAP so we can immediately start our own research).

**Comment by juliaalexis** [comment]
You can contact me on m.me/julialexis.diaz (deactivated my FB sorry huhu), I'm free tomorrow night!

**Comment by jechnology** [comment]
Sent you a message @juliaalexis pls check your message requests

**Comment by juliaalexis** [comment]
> Sent you a message @juliaalexis pls check your message requests
> 

thank you! waiting for the others :)

**Comment by gerolddelacruz** [comment]
Mine is https://m.me/gerolddelacruz. Thanks @jechnology

**Comment by juliaalexis** [comment]
> Mine is https://m.me/gerolddelacruz. Thanks @jechnology

Thanks, Gerold! Messaged you earlier already, please check your message requests :) I also messaged @joeldoctor47 but I'm not sure if it's his account (sana oo lol).
