### ISSUE TITLE
Research and Writing 

### ISSUE THREAD

**Issue by jechnology** [jechnology/mms142-groupe-2020#4]
1. What is IoT - Daizy
   a. Brief history of IoT
   b. IoT concepts
   c. General example of IoT
2. Advantages of IoT - Julia
   a. Environment
   b. Efficiency
3. Application in Industries - Jameson, Asaph
   a. Agriculture
   b. Medical
   c. Manufacturing
   d. Retail, etc
4. Challenges with IoT - Joel
   a. Privacy
   b. Security, etc
   c. Environmental
5. Real life examples - Gerold, Joshua

Deadline on December 4

**Comment by gerolddelacruz** [comment]
Added Real-Life IoT Examples in our Wiki. Let's go team!
